project_id = "ljauuejvmnufzqjwybrc"

[functions.study-chat]
enabled = true
verify_jwt = false

[functions.extract-puskica]
enabled = true
verify_jwt = false

[functions.find-user]
enabled = true
verify_jwt = false

[functions.validate-license]
enabled = true
verify_jwt = false
