import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "sr" | "en" | "de" | "fr" | "es" | "it" | "ru" | "zh" | "ja" | "ar";

interface Translations {
  menu: string;
  lightMode: string;
  darkMode: string;
  editProfile: string;
  chatHistory: string;
  clearHistory: string;
  checkUpdates: string;
  admin: string;
  signOut: string;
  upgradeToPro: string;
  languages: string;
  askAnything: string;
  takePhoto: string;
  chooseFromGallery: string;
  sharePdf: string;
  voiceChat: string;
  send: string;
  days: string;
  lifetimePro: string;
  cancel: string;
  enter: string;
  password: string;
  wrongPassword: string;
  checkingUpdates: string;
  pleaseWait: string;
  error: string;
  cannotCheckUpdate: string;
  addMessage: string;
  askAboutImage: string;
  speakNow: string;
  listening: string;
  processing: string;
  tapToSpeak: string;
  stopListening: string;
  // Puskice Section
  myPuskice: string;
  unlimited: string;
  remainingToday: string;
  newNote: string;
  aiFastPuskica: string;
  uploadImageDescription: string;
  subjectPlaceholder: string;
  changeImage: string;
  addImage: string;
  extracting: string;
  create: string;
  historyBySubjects: string;
  total: string;
  noPuskiceYet: string;
  uploadImageForExtraction: string;
  puskica: string;
  close: string;
  pleaseEnterSubject: string;
  pleaseAddImage: string;
  mustBeLoggedIn: string;
  extractionFailed: string;
  success: string;
  aiExtractedInfo: string;
  somethingWentWrong: string;
  cannotDeletePuskica: string;
  deleted: string;
  puskicaDeleted: string;
  other: string;
  puskiceCount: string;
  // Direct Chat
  messages: string;
  newChat: string;
  enterUserEmail: string;
  userNotFound: string;
  noUserWithEmail: string;
  cannotMessageSelf: string;
  conversationCreated: string;
  canNowChatWith: string;
  cannotCreateConversation: string;
  messageNotSent: string;
  noMessages: string;
  startConversation: string;
  unknown: string;
  // Quick Actions
  explainSimply: string;
  createSummary: string;
  makeQuiz: string;
  helpWithHomework: string;
  examMode: string;
  explainPrompt: string;
  summaryPrompt: string;
  quizPrompt: string;
  homeworkPrompt: string;
  examPrompt: string;
  // Welcome Message
  heyThere: string;
  personalTutor: string;
  tryTyping: string;
  homeworkHelp: string;
  understandTopics: string;
  practiceQuizzes: string;
  // Tabs
  aiChat: string;
  puskiceTab: string;
  messagesTab: string;
}

const translations: Record<Language, Translations> = {
  sr: {
    menu: "Meni",
    lightMode: "Svetli režim",
    darkMode: "Tamni režim",
    editProfile: "Uredi profil / Avatar",
    chatHistory: "Istorija ćaskanja",
    clearHistory: "Obriši istoriju",
    checkUpdates: "Proveri ažuriranje",
    admin: "Admin",
    signOut: "Odjavi se",
    upgradeToPro: "Nadogradi na Pro",
    languages: "Jezici",
    askAnything: "Pitaj bilo šta...",
    takePhoto: "Slikaj",
    chooseFromGallery: "Izaberi iz galerije",
    sharePdf: "Podeli PDF",
    voiceChat: "Glasovni čet",
    send: "Pošalji",
    days: "dana",
    lifetimePro: "Lifetime Pro",
    cancel: "Odustani",
    enter: "Uđi",
    password: "Šifra...",
    wrongPassword: "Pogrešna šifra",
    checkingUpdates: "Provera ažuriranja…",
    pleaseWait: "Molimo sačekaj.",
    error: "Greška",
    cannotCheckUpdate: "Nije moguće proveriti ažuriranje.",
    addMessage: "Dodaj poruku...",
    askAboutImage: "Pitaj o ovoj slici...",
    speakNow: "Govori sada",
    listening: "Slušam...",
    processing: "Obrađujem...",
    tapToSpeak: "Dodirni za govor",
    stopListening: "Zaustavi",
    // Puskice
    myPuskice: "Moje Puškice",
    unlimited: "Neograničeno",
    remainingToday: "Preostalo danas",
    newNote: "Nova",
    aiFastPuskica: "AI Brza Puškica",
    uploadImageDescription: "Uploaduj sliku i unesi predmet - AI automatski ekstrahira formule, definicije, datume i ključne osobe!",
    subjectPlaceholder: "Naziv predmeta (npr. Matematika)",
    changeImage: "Promeni sliku",
    addImage: "Dodaj sliku",
    extracting: "Ekstrahiram...",
    create: "Kreiraj",
    historyBySubjects: "Istorija po Predmetima",
    total: "ukupno",
    noPuskiceYet: "Nemaš još puškica",
    uploadImageForExtraction: "Uploaduj sliku i unesi predmet gore za brzu AI ekstrakciju!",
    puskica: "Puškica",
    close: "Zatvori",
    pleaseEnterSubject: "Molimo unesi naziv predmeta.",
    pleaseAddImage: "Molimo dodaj sliku za ekstrakciju.",
    mustBeLoggedIn: "Morate biti prijavljeni.",
    extractionFailed: "Ekstrakcija nije uspela",
    success: "Uspešno! ✨",
    aiExtractedInfo: "AI je ekstrahirao informacije i kreirao puškicu.",
    somethingWentWrong: "Nešto nije u redu.",
    cannotDeletePuskica: "Nije moguće obrisati puškicu.",
    deleted: "Obrisano",
    puskicaDeleted: "Puškica je obrisana.",
    other: "Ostalo",
    puskiceCount: "puškica",
    // Direct Chat
    messages: "Poruke",
    newChat: "Novi chat",
    enterUserEmail: "Unesi email korisnika kojem želiš pisati:",
    userNotFound: "Korisnik nije pronađen",
    noUserWithEmail: "Nema korisnika sa tom email adresom.",
    cannotMessageSelf: "Ne možeš slati poruke sebi.",
    conversationCreated: "Razgovor kreiran",
    canNowChatWith: "Možeš sada pisati sa",
    cannotCreateConversation: "Nije moguće kreirati razgovor.",
    messageNotSent: "Poruka nije poslana.",
    noMessages: "Nema poruka",
    startConversation: "Započni razgovor sa nekim!",
    unknown: "Nepoznato",
    // Quick Actions
    explainSimply: "Objasni Jednostavno",
    createSummary: "Napravi Rezime",
    makeQuiz: "Napravi Kviz",
    helpWithHomework: "Pomoć sa Domaćim",
    examMode: "Režim Ispita",
    explainPrompt: "Molim te objasni ovu temu na najjednostavniji način, korak po korak:",
    summaryPrompt: "Molim te napravi jasan, organizovan rezime ove teme:",
    quizPrompt: "Molim te napravi kratki kviz sa 5 pitanja sa više odgovora o:",
    homeworkPrompt: "Treba mi pomoć sa domaćim zadatkom. Molim te vodi me kroz ovaj problem:",
    examPrompt: "Spremam se za ispit. Molim te daj mi direktne, jasne odgovore:",
    // Welcome Message
    heyThere: "Ćao! 👋",
    personalTutor: "Ja sam tvoj lični AI tutor. Ovde sam da ti pomognem da učiš, razumeš teške teme i postigneš odlične rezultate. Šta bi želeo da naučiš danas?",
    tryTyping: "Probaj ukucati pitanje ili koristi brze akcije ispod ✨",
    homeworkHelp: "Pomoć sa domaćim korak po korak",
    understandTopics: "Razumevanje teških tema lako",
    practiceQuizzes: "Vežbaj sa kvizovima",
    // Tabs
    aiChat: "AI Čet",
    puskiceTab: "Puškice",
    messagesTab: "Poruke",
  },
  en: {
    menu: "Menu",
    lightMode: "Light mode",
    darkMode: "Dark mode",
    editProfile: "Edit profile / Avatar",
    chatHistory: "Chat history",
    clearHistory: "Clear history",
    checkUpdates: "Check for updates",
    admin: "Admin",
    signOut: "Sign out",
    upgradeToPro: "Upgrade to Pro",
    languages: "Languages",
    askAnything: "Ask anything...",
    takePhoto: "Take photo",
    chooseFromGallery: "Choose from gallery",
    sharePdf: "Share PDF",
    voiceChat: "Voice chat",
    send: "Send",
    days: "days",
    lifetimePro: "Lifetime Pro",
    cancel: "Cancel",
    enter: "Enter",
    password: "Password...",
    wrongPassword: "Wrong password",
    checkingUpdates: "Checking for updates…",
    pleaseWait: "Please wait.",
    error: "Error",
    cannotCheckUpdate: "Cannot check for updates.",
    addMessage: "Add a message...",
    askAboutImage: "Ask about this image...",
    speakNow: "Speak now",
    listening: "Listening...",
    processing: "Processing...",
    tapToSpeak: "Tap to speak",
    stopListening: "Stop",
    // Puskice
    myPuskice: "My Notes",
    unlimited: "Unlimited",
    remainingToday: "Remaining today",
    newNote: "New",
    aiFastPuskica: "AI Quick Note",
    uploadImageDescription: "Upload an image and enter subject - AI automatically extracts formulas, definitions, dates and key people!",
    subjectPlaceholder: "Subject name (e.g., Math)",
    changeImage: "Change image",
    addImage: "Add image",
    extracting: "Extracting...",
    create: "Create",
    historyBySubjects: "History by Subjects",
    total: "total",
    noPuskiceYet: "No notes yet",
    uploadImageForExtraction: "Upload an image and enter subject above for quick AI extraction!",
    puskica: "Note",
    close: "Close",
    pleaseEnterSubject: "Please enter subject name.",
    pleaseAddImage: "Please add an image for extraction.",
    mustBeLoggedIn: "You must be logged in.",
    extractionFailed: "Extraction failed",
    success: "Success! ✨",
    aiExtractedInfo: "AI extracted information and created a note.",
    somethingWentWrong: "Something went wrong.",
    cannotDeletePuskica: "Cannot delete note.",
    deleted: "Deleted",
    puskicaDeleted: "Note has been deleted.",
    other: "Other",
    puskiceCount: "notes",
    // Direct Chat
    messages: "Messages",
    newChat: "New chat",
    enterUserEmail: "Enter email of user you want to message:",
    userNotFound: "User not found",
    noUserWithEmail: "No user with that email address.",
    cannotMessageSelf: "You cannot message yourself.",
    conversationCreated: "Conversation created",
    canNowChatWith: "You can now chat with",
    cannotCreateConversation: "Cannot create conversation.",
    messageNotSent: "Message not sent.",
    noMessages: "No messages",
    startConversation: "Start a conversation with someone!",
    unknown: "Unknown",
    // Quick Actions
    explainSimply: "Explain Simply",
    createSummary: "Create Summary",
    makeQuiz: "Make Quiz",
    helpWithHomework: "Help with Homework",
    examMode: "Exam Mode",
    explainPrompt: "Please explain this topic in the simplest way possible, step by step:",
    summaryPrompt: "Please create a clear, organized summary of this topic:",
    quizPrompt: "Please create a short quiz with 5 multiple-choice questions about:",
    homeworkPrompt: "I need help with my homework. Please guide me through this problem:",
    examPrompt: "I'm preparing for an exam. Please give me direct, clear answers:",
    // Welcome Message
    heyThere: "Hey there! 👋",
    personalTutor: "I'm your personal AI tutor. I'm here to help you learn, understand tricky topics, and ace your studies. What would you like to learn today?",
    tryTyping: "Try typing a question or use the quick action buttons below ✨",
    homeworkHelp: "Get homework help step-by-step",
    understandTopics: "Understand difficult topics easily",
    practiceQuizzes: "Practice with quizzes",
    // Tabs
    aiChat: "AI Chat",
    puskiceTab: "Notes",
    messagesTab: "Messages",
  },
  de: {
    menu: "Menü",
    lightMode: "Heller Modus",
    darkMode: "Dunkler Modus",
    editProfile: "Profil bearbeiten / Avatar",
    chatHistory: "Chat-Verlauf",
    clearHistory: "Verlauf löschen",
    checkUpdates: "Nach Updates suchen",
    admin: "Admin",
    signOut: "Abmelden",
    upgradeToPro: "Auf Pro upgraden",
    languages: "Sprachen",
    askAnything: "Frag etwas...",
    takePhoto: "Foto aufnehmen",
    chooseFromGallery: "Aus Galerie wählen",
    sharePdf: "PDF teilen",
    voiceChat: "Sprachchat",
    send: "Senden",
    days: "Tage",
    lifetimePro: "Lifetime Pro",
    cancel: "Abbrechen",
    enter: "Eingeben",
    password: "Passwort...",
    wrongPassword: "Falsches Passwort",
    checkingUpdates: "Suche nach Updates…",
    pleaseWait: "Bitte warten.",
    error: "Fehler",
    cannotCheckUpdate: "Updates können nicht überprüft werden.",
    addMessage: "Nachricht hinzufügen...",
    askAboutImage: "Frag zu diesem Bild...",
    speakNow: "Jetzt sprechen",
    listening: "Höre zu...",
    processing: "Verarbeite...",
    tapToSpeak: "Tippen zum Sprechen",
    stopListening: "Stopp",
    // Puskice
    myPuskice: "Meine Notizen",
    unlimited: "Unbegrenzt",
    remainingToday: "Heute verbleibend",
    newNote: "Neu",
    aiFastPuskica: "KI Schnellnotiz",
    uploadImageDescription: "Bild hochladen und Fach eingeben - KI extrahiert automatisch Formeln, Definitionen, Daten und Schlüsselpersonen!",
    subjectPlaceholder: "Fachname (z.B. Mathematik)",
    changeImage: "Bild ändern",
    addImage: "Bild hinzufügen",
    extracting: "Extrahiere...",
    create: "Erstellen",
    historyBySubjects: "Verlauf nach Fächern",
    total: "gesamt",
    noPuskiceYet: "Noch keine Notizen",
    uploadImageForExtraction: "Lade ein Bild hoch und gib das Fach oben für schnelle KI-Extraktion ein!",
    puskica: "Notiz",
    close: "Schließen",
    pleaseEnterSubject: "Bitte Fachname eingeben.",
    pleaseAddImage: "Bitte Bild für Extraktion hinzufügen.",
    mustBeLoggedIn: "Sie müssen angemeldet sein.",
    extractionFailed: "Extraktion fehlgeschlagen",
    success: "Erfolg! ✨",
    aiExtractedInfo: "KI hat Informationen extrahiert und Notiz erstellt.",
    somethingWentWrong: "Etwas ist schief gelaufen.",
    cannotDeletePuskica: "Notiz kann nicht gelöscht werden.",
    deleted: "Gelöscht",
    puskicaDeleted: "Notiz wurde gelöscht.",
    other: "Sonstiges",
    puskiceCount: "Notizen",
    // Direct Chat
    messages: "Nachrichten",
    newChat: "Neuer Chat",
    enterUserEmail: "E-Mail des Benutzers eingeben, dem Sie schreiben möchten:",
    userNotFound: "Benutzer nicht gefunden",
    noUserWithEmail: "Kein Benutzer mit dieser E-Mail-Adresse.",
    cannotMessageSelf: "Sie können sich nicht selbst schreiben.",
    conversationCreated: "Unterhaltung erstellt",
    canNowChatWith: "Sie können jetzt chatten mit",
    cannotCreateConversation: "Unterhaltung kann nicht erstellt werden.",
    messageNotSent: "Nachricht nicht gesendet.",
    noMessages: "Keine Nachrichten",
    startConversation: "Starten Sie ein Gespräch mit jemandem!",
    unknown: "Unbekannt",
    // Quick Actions
    explainSimply: "Einfach erklären",
    createSummary: "Zusammenfassung",
    makeQuiz: "Quiz erstellen",
    helpWithHomework: "Hausaufgabenhilfe",
    examMode: "Prüfungsmodus",
    explainPrompt: "Bitte erklär dieses Thema auf einfachste Weise, Schritt für Schritt:",
    summaryPrompt: "Bitte erstelle eine klare, organisierte Zusammenfassung dieses Themas:",
    quizPrompt: "Bitte erstelle ein kurzes Quiz mit 5 Multiple-Choice-Fragen über:",
    homeworkPrompt: "Ich brauche Hilfe bei meinen Hausaufgaben. Bitte führe mich durch dieses Problem:",
    examPrompt: "Ich bereite mich auf eine Prüfung vor. Bitte gib mir direkte, klare Antworten:",
    // Welcome Message
    heyThere: "Hallo! 👋",
    personalTutor: "Ich bin dein persönlicher KI-Tutor. Ich bin hier, um dir beim Lernen zu helfen, schwierige Themen zu verstehen und deine Studien zu meistern. Was möchtest du heute lernen?",
    tryTyping: "Versuche eine Frage zu tippen oder nutze die Schnellaktionen unten ✨",
    homeworkHelp: "Hausaufgabenhilfe Schritt für Schritt",
    understandTopics: "Schwierige Themen leicht verstehen",
    practiceQuizzes: "Mit Quizzen üben",
    // Tabs
    aiChat: "KI Chat",
    puskiceTab: "Notizen",
    messagesTab: "Nachrichten",
  },
  fr: {
    menu: "Menu",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    editProfile: "Modifier profil / Avatar",
    chatHistory: "Historique des chats",
    clearHistory: "Effacer l'historique",
    checkUpdates: "Vérifier les mises à jour",
    admin: "Admin",
    signOut: "Déconnexion",
    upgradeToPro: "Passer à Pro",
    languages: "Langues",
    askAnything: "Posez une question...",
    takePhoto: "Prendre une photo",
    chooseFromGallery: "Choisir de la galerie",
    sharePdf: "Partager PDF",
    voiceChat: "Chat vocal",
    send: "Envoyer",
    days: "jours",
    lifetimePro: "Lifetime Pro",
    cancel: "Annuler",
    enter: "Entrer",
    password: "Mot de passe...",
    wrongPassword: "Mot de passe incorrect",
    checkingUpdates: "Vérification des mises à jour…",
    pleaseWait: "Veuillez patienter.",
    error: "Erreur",
    cannotCheckUpdate: "Impossible de vérifier les mises à jour.",
    addMessage: "Ajouter un message...",
    askAboutImage: "Posez une question sur cette image...",
    speakNow: "Parlez maintenant",
    listening: "Écoute...",
    processing: "Traitement...",
    tapToSpeak: "Appuyez pour parler",
    stopListening: "Arrêter",
    // Puskice
    myPuskice: "Mes Notes",
    unlimited: "Illimité",
    remainingToday: "Restant aujourd'hui",
    newNote: "Nouveau",
    aiFastPuskica: "Note Rapide IA",
    uploadImageDescription: "Téléchargez une image et entrez la matière - l'IA extrait automatiquement les formules, définitions, dates et personnes clés!",
    subjectPlaceholder: "Nom de la matière (ex. Maths)",
    changeImage: "Changer l'image",
    addImage: "Ajouter une image",
    extracting: "Extraction...",
    create: "Créer",
    historyBySubjects: "Historique par Matières",
    total: "total",
    noPuskiceYet: "Pas encore de notes",
    uploadImageForExtraction: "Téléchargez une image et entrez la matière ci-dessus pour une extraction IA rapide!",
    puskica: "Note",
    close: "Fermer",
    pleaseEnterSubject: "Veuillez entrer le nom de la matière.",
    pleaseAddImage: "Veuillez ajouter une image pour l'extraction.",
    mustBeLoggedIn: "Vous devez être connecté.",
    extractionFailed: "Échec de l'extraction",
    success: "Succès! ✨",
    aiExtractedInfo: "L'IA a extrait les informations et créé une note.",
    somethingWentWrong: "Quelque chose s'est mal passé.",
    cannotDeletePuskica: "Impossible de supprimer la note.",
    deleted: "Supprimé",
    puskicaDeleted: "La note a été supprimée.",
    other: "Autre",
    puskiceCount: "notes",
    // Direct Chat
    messages: "Messages",
    newChat: "Nouveau chat",
    enterUserEmail: "Entrez l'email de l'utilisateur à qui vous voulez écrire:",
    userNotFound: "Utilisateur non trouvé",
    noUserWithEmail: "Aucun utilisateur avec cette adresse email.",
    cannotMessageSelf: "Vous ne pouvez pas vous envoyer de message.",
    conversationCreated: "Conversation créée",
    canNowChatWith: "Vous pouvez maintenant discuter avec",
    cannotCreateConversation: "Impossible de créer la conversation.",
    messageNotSent: "Message non envoyé.",
    noMessages: "Pas de messages",
    startConversation: "Commencez une conversation avec quelqu'un!",
    unknown: "Inconnu",
    // Quick Actions
    explainSimply: "Expliquer Simplement",
    createSummary: "Créer un Résumé",
    makeQuiz: "Faire un Quiz",
    helpWithHomework: "Aide aux Devoirs",
    examMode: "Mode Examen",
    explainPrompt: "Expliquez ce sujet de la manière la plus simple possible, étape par étape:",
    summaryPrompt: "Créez un résumé clair et organisé de ce sujet:",
    quizPrompt: "Créez un court quiz avec 5 questions à choix multiples sur:",
    homeworkPrompt: "J'ai besoin d'aide pour mes devoirs. Guidez-moi à travers ce problème:",
    examPrompt: "Je prépare un examen. Donnez-moi des réponses directes et claires:",
    // Welcome Message
    heyThere: "Salut! 👋",
    personalTutor: "Je suis votre tuteur IA personnel. Je suis là pour vous aider à apprendre, comprendre les sujets difficiles et réussir vos études. Que voulez-vous apprendre aujourd'hui?",
    tryTyping: "Essayez de taper une question ou utilisez les boutons d'action rapide ci-dessous ✨",
    homeworkHelp: "Aide aux devoirs étape par étape",
    understandTopics: "Comprendre facilement les sujets difficiles",
    practiceQuizzes: "S'entraîner avec des quiz",
    // Tabs
    aiChat: "Chat IA",
    puskiceTab: "Notes",
    messagesTab: "Messages",
  },
  es: {
    menu: "Menú",
    lightMode: "Modo claro",
    darkMode: "Modo oscuro",
    editProfile: "Editar perfil / Avatar",
    chatHistory: "Historial de chat",
    clearHistory: "Borrar historial",
    checkUpdates: "Buscar actualizaciones",
    admin: "Admin",
    signOut: "Cerrar sesión",
    upgradeToPro: "Actualizar a Pro",
    languages: "Idiomas",
    askAnything: "Pregunta lo que sea...",
    takePhoto: "Tomar foto",
    chooseFromGallery: "Elegir de galería",
    sharePdf: "Compartir PDF",
    voiceChat: "Chat de voz",
    send: "Enviar",
    days: "días",
    lifetimePro: "Lifetime Pro",
    cancel: "Cancelar",
    enter: "Entrar",
    password: "Contraseña...",
    wrongPassword: "Contraseña incorrecta",
    checkingUpdates: "Buscando actualizaciones…",
    pleaseWait: "Por favor espera.",
    error: "Error",
    cannotCheckUpdate: "No se puede verificar actualizaciones.",
    addMessage: "Añadir mensaje...",
    askAboutImage: "Pregunta sobre esta imagen...",
    speakNow: "Habla ahora",
    listening: "Escuchando...",
    processing: "Procesando...",
    tapToSpeak: "Toca para hablar",
    stopListening: "Detener",
    // Puskice
    myPuskice: "Mis Notas",
    unlimited: "Ilimitado",
    remainingToday: "Restante hoy",
    newNote: "Nueva",
    aiFastPuskica: "Nota Rápida IA",
    uploadImageDescription: "Sube una imagen e ingresa la materia - ¡la IA extrae automáticamente fórmulas, definiciones, fechas y personas clave!",
    subjectPlaceholder: "Nombre de la materia (ej. Matemáticas)",
    changeImage: "Cambiar imagen",
    addImage: "Añadir imagen",
    extracting: "Extrayendo...",
    create: "Crear",
    historyBySubjects: "Historial por Materias",
    total: "total",
    noPuskiceYet: "Aún no hay notas",
    uploadImageForExtraction: "¡Sube una imagen e ingresa la materia arriba para extracción rápida con IA!",
    puskica: "Nota",
    close: "Cerrar",
    pleaseEnterSubject: "Por favor ingresa el nombre de la materia.",
    pleaseAddImage: "Por favor añade una imagen para extracción.",
    mustBeLoggedIn: "Debes iniciar sesión.",
    extractionFailed: "Falló la extracción",
    success: "¡Éxito! ✨",
    aiExtractedInfo: "La IA extrajo información y creó una nota.",
    somethingWentWrong: "Algo salió mal.",
    cannotDeletePuskica: "No se puede eliminar la nota.",
    deleted: "Eliminado",
    puskicaDeleted: "La nota ha sido eliminada.",
    other: "Otro",
    puskiceCount: "notas",
    // Direct Chat
    messages: "Mensajes",
    newChat: "Nuevo chat",
    enterUserEmail: "Ingresa el email del usuario al que quieres escribir:",
    userNotFound: "Usuario no encontrado",
    noUserWithEmail: "No hay usuario con ese email.",
    cannotMessageSelf: "No puedes enviarte mensajes a ti mismo.",
    conversationCreated: "Conversación creada",
    canNowChatWith: "Ahora puedes chatear con",
    cannotCreateConversation: "No se puede crear conversación.",
    messageNotSent: "Mensaje no enviado.",
    noMessages: "Sin mensajes",
    startConversation: "¡Inicia una conversación con alguien!",
    unknown: "Desconocido",
    // Quick Actions
    explainSimply: "Explicar Simple",
    createSummary: "Crear Resumen",
    makeQuiz: "Hacer Quiz",
    helpWithHomework: "Ayuda con Tarea",
    examMode: "Modo Examen",
    explainPrompt: "Por favor explica este tema de la manera más simple posible, paso a paso:",
    summaryPrompt: "Por favor crea un resumen claro y organizado de este tema:",
    quizPrompt: "Por favor crea un quiz corto con 5 preguntas de opción múltiple sobre:",
    homeworkPrompt: "Necesito ayuda con mi tarea. Por favor guíame a través de este problema:",
    examPrompt: "Me estoy preparando para un examen. Por favor dame respuestas directas y claras:",
    // Welcome Message
    heyThere: "¡Hola! 👋",
    personalTutor: "Soy tu tutor IA personal. Estoy aquí para ayudarte a aprender, entender temas difíciles y triunfar en tus estudios. ¿Qué te gustaría aprender hoy?",
    tryTyping: "Intenta escribir una pregunta o usa los botones de acción rápida abajo ✨",
    homeworkHelp: "Ayuda con tareas paso a paso",
    understandTopics: "Entiende temas difíciles fácilmente",
    practiceQuizzes: "Practica con quizzes",
    // Tabs
    aiChat: "Chat IA",
    puskiceTab: "Notas",
    messagesTab: "Mensajes",
  },
  it: {
    menu: "Menu",
    lightMode: "Modalità chiara",
    darkMode: "Modalità scura",
    editProfile: "Modifica profilo / Avatar",
    chatHistory: "Cronologia chat",
    clearHistory: "Cancella cronologia",
    checkUpdates: "Controlla aggiornamenti",
    admin: "Admin",
    signOut: "Esci",
    upgradeToPro: "Passa a Pro",
    languages: "Lingue",
    askAnything: "Chiedi qualsiasi cosa...",
    takePhoto: "Scatta foto",
    chooseFromGallery: "Scegli dalla galleria",
    sharePdf: "Condividi PDF",
    voiceChat: "Chat vocale",
    send: "Invia",
    days: "giorni",
    lifetimePro: "Lifetime Pro",
    cancel: "Annulla",
    enter: "Entra",
    password: "Password...",
    wrongPassword: "Password errata",
    checkingUpdates: "Controllo aggiornamenti…",
    pleaseWait: "Attendere prego.",
    error: "Errore",
    cannotCheckUpdate: "Impossibile verificare aggiornamenti.",
    addMessage: "Aggiungi messaggio...",
    askAboutImage: "Chiedi di questa immagine...",
    speakNow: "Parla ora",
    listening: "Ascolto...",
    processing: "Elaborazione...",
    tapToSpeak: "Tocca per parlare",
    stopListening: "Ferma",
    // Puskice
    myPuskice: "Le Mie Note",
    unlimited: "Illimitato",
    remainingToday: "Rimanenti oggi",
    newNote: "Nuova",
    aiFastPuskica: "Nota Rapida IA",
    uploadImageDescription: "Carica un'immagine e inserisci la materia - l'IA estrae automaticamente formule, definizioni, date e persone chiave!",
    subjectPlaceholder: "Nome materia (es. Matematica)",
    changeImage: "Cambia immagine",
    addImage: "Aggiungi immagine",
    extracting: "Estrazione...",
    create: "Crea",
    historyBySubjects: "Cronologia per Materie",
    total: "totale",
    noPuskiceYet: "Ancora nessuna nota",
    uploadImageForExtraction: "Carica un'immagine e inserisci la materia sopra per l'estrazione rapida IA!",
    puskica: "Nota",
    close: "Chiudi",
    pleaseEnterSubject: "Inserisci il nome della materia.",
    pleaseAddImage: "Aggiungi un'immagine per l'estrazione.",
    mustBeLoggedIn: "Devi essere connesso.",
    extractionFailed: "Estrazione fallita",
    success: "Successo! ✨",
    aiExtractedInfo: "L'IA ha estratto le informazioni e creato una nota.",
    somethingWentWrong: "Qualcosa è andato storto.",
    cannotDeletePuskica: "Impossibile eliminare la nota.",
    deleted: "Eliminato",
    puskicaDeleted: "La nota è stata eliminata.",
    other: "Altro",
    puskiceCount: "note",
    // Direct Chat
    messages: "Messaggi",
    newChat: "Nuova chat",
    enterUserEmail: "Inserisci l'email dell'utente a cui vuoi scrivere:",
    userNotFound: "Utente non trovato",
    noUserWithEmail: "Nessun utente con questa email.",
    cannotMessageSelf: "Non puoi inviare messaggi a te stesso.",
    conversationCreated: "Conversazione creata",
    canNowChatWith: "Ora puoi chattare con",
    cannotCreateConversation: "Impossibile creare conversazione.",
    messageNotSent: "Messaggio non inviato.",
    noMessages: "Nessun messaggio",
    startConversation: "Inizia una conversazione con qualcuno!",
    unknown: "Sconosciuto",
    // Quick Actions
    explainSimply: "Spiega Semplicemente",
    createSummary: "Crea Riassunto",
    makeQuiz: "Crea Quiz",
    helpWithHomework: "Aiuto Compiti",
    examMode: "Modalità Esame",
    explainPrompt: "Per favore spiega questo argomento nel modo più semplice possibile, passo dopo passo:",
    summaryPrompt: "Per favore crea un riassunto chiaro e organizzato di questo argomento:",
    quizPrompt: "Per favore crea un breve quiz con 5 domande a scelta multipla su:",
    homeworkPrompt: "Ho bisogno di aiuto con i miei compiti. Per favore guidami attraverso questo problema:",
    examPrompt: "Mi sto preparando per un esame. Per favore dammi risposte dirette e chiare:",
    // Welcome Message
    heyThere: "Ciao! 👋",
    personalTutor: "Sono il tuo tutor IA personale. Sono qui per aiutarti a imparare, capire argomenti difficili e avere successo negli studi. Cosa vorresti imparare oggi?",
    tryTyping: "Prova a digitare una domanda o usa i pulsanti di azione rapida sotto ✨",
    homeworkHelp: "Aiuto compiti passo dopo passo",
    understandTopics: "Comprendi facilmente argomenti difficili",
    practiceQuizzes: "Esercitati con i quiz",
    // Tabs
    aiChat: "Chat IA",
    puskiceTab: "Note",
    messagesTab: "Messaggi",
  },
  ru: {
    menu: "Меню",
    lightMode: "Светлый режим",
    darkMode: "Тёмный режим",
    editProfile: "Редактировать профиль / Аватар",
    chatHistory: "История чата",
    clearHistory: "Очистить историю",
    checkUpdates: "Проверить обновления",
    admin: "Админ",
    signOut: "Выйти",
    upgradeToPro: "Перейти на Pro",
    languages: "Языки",
    askAnything: "Спроси что угодно...",
    takePhoto: "Сделать фото",
    chooseFromGallery: "Выбрать из галереи",
    sharePdf: "Поделиться PDF",
    voiceChat: "Голосовой чат",
    send: "Отправить",
    days: "дней",
    lifetimePro: "Lifetime Pro",
    cancel: "Отмена",
    enter: "Войти",
    password: "Пароль...",
    wrongPassword: "Неверный пароль",
    checkingUpdates: "Проверка обновлений…",
    pleaseWait: "Пожалуйста, подождите.",
    error: "Ошибка",
    cannotCheckUpdate: "Не удается проверить обновления.",
    addMessage: "Добавить сообщение...",
    askAboutImage: "Спросить об этом изображении...",
    speakNow: "Говорите сейчас",
    listening: "Слушаю...",
    processing: "Обработка...",
    tapToSpeak: "Нажмите, чтобы говорить",
    stopListening: "Стоп",
    // Puskice
    myPuskice: "Мои Заметки",
    unlimited: "Безлимитно",
    remainingToday: "Осталось сегодня",
    newNote: "Новая",
    aiFastPuskica: "Быстрая Заметка ИИ",
    uploadImageDescription: "Загрузите изображение и введите предмет - ИИ автоматически извлечёт формулы, определения, даты и ключевых людей!",
    subjectPlaceholder: "Название предмета (напр. Математика)",
    changeImage: "Изменить изображение",
    addImage: "Добавить изображение",
    extracting: "Извлечение...",
    create: "Создать",
    historyBySubjects: "История по Предметам",
    total: "всего",
    noPuskiceYet: "Пока нет заметок",
    uploadImageForExtraction: "Загрузите изображение и введите предмет выше для быстрого извлечения ИИ!",
    puskica: "Заметка",
    close: "Закрыть",
    pleaseEnterSubject: "Пожалуйста, введите название предмета.",
    pleaseAddImage: "Пожалуйста, добавьте изображение для извлечения.",
    mustBeLoggedIn: "Вы должны войти в систему.",
    extractionFailed: "Извлечение не удалось",
    success: "Успех! ✨",
    aiExtractedInfo: "ИИ извлёк информацию и создал заметку.",
    somethingWentWrong: "Что-то пошло не так.",
    cannotDeletePuskica: "Невозможно удалить заметку.",
    deleted: "Удалено",
    puskicaDeleted: "Заметка удалена.",
    other: "Другое",
    puskiceCount: "заметок",
    // Direct Chat
    messages: "Сообщения",
    newChat: "Новый чат",
    enterUserEmail: "Введите email пользователя, которому хотите написать:",
    userNotFound: "Пользователь не найден",
    noUserWithEmail: "Нет пользователя с таким email.",
    cannotMessageSelf: "Вы не можете писать себе.",
    conversationCreated: "Разговор создан",
    canNowChatWith: "Теперь вы можете писать с",
    cannotCreateConversation: "Невозможно создать разговор.",
    messageNotSent: "Сообщение не отправлено.",
    noMessages: "Нет сообщений",
    startConversation: "Начните разговор с кем-нибудь!",
    unknown: "Неизвестно",
    // Quick Actions
    explainSimply: "Объясни Просто",
    createSummary: "Создать Резюме",
    makeQuiz: "Сделать Тест",
    helpWithHomework: "Помощь с Домашкой",
    examMode: "Режим Экзамена",
    explainPrompt: "Пожалуйста, объясни эту тему максимально просто, шаг за шагом:",
    summaryPrompt: "Пожалуйста, создай чёткое, организованное резюме этой темы:",
    quizPrompt: "Пожалуйста, создай короткий тест с 5 вопросами с множественным выбором о:",
    homeworkPrompt: "Мне нужна помощь с домашним заданием. Пожалуйста, проведи меня через эту задачу:",
    examPrompt: "Я готовлюсь к экзамену. Пожалуйста, дай мне прямые, чёткие ответы:",
    // Welcome Message
    heyThere: "Привет! 👋",
    personalTutor: "Я твой личный ИИ-репетитор. Я здесь, чтобы помочь тебе учиться, понимать сложные темы и преуспевать в учёбе. Что бы ты хотел изучить сегодня?",
    tryTyping: "Попробуй ввести вопрос или используй кнопки быстрых действий ниже ✨",
    homeworkHelp: "Помощь с домашним заданием пошагово",
    understandTopics: "Легко понимай сложные темы",
    practiceQuizzes: "Практикуйся с тестами",
    // Tabs
    aiChat: "ИИ Чат",
    puskiceTab: "Заметки",
    messagesTab: "Сообщения",
  },
  zh: {
    menu: "菜单",
    lightMode: "浅色模式",
    darkMode: "深色模式",
    editProfile: "编辑个人资料 / 头像",
    chatHistory: "聊天记录",
    clearHistory: "清除记录",
    checkUpdates: "检查更新",
    admin: "管理员",
    signOut: "退出",
    upgradeToPro: "升级到 Pro",
    languages: "语言",
    askAnything: "问任何问题...",
    takePhoto: "拍照",
    chooseFromGallery: "从相册选择",
    sharePdf: "分享 PDF",
    voiceChat: "语音聊天",
    send: "发送",
    days: "天",
    lifetimePro: "终身 Pro",
    cancel: "取消",
    enter: "进入",
    password: "密码...",
    wrongPassword: "密码错误",
    checkingUpdates: "检查更新中…",
    pleaseWait: "请稍候。",
    error: "错误",
    cannotCheckUpdate: "无法检查更新。",
    addMessage: "添加消息...",
    askAboutImage: "询问关于这张图片...",
    speakNow: "现在说话",
    listening: "正在听...",
    processing: "处理中...",
    tapToSpeak: "点击说话",
    stopListening: "停止",
    // Puskice
    myPuskice: "我的笔记",
    unlimited: "无限",
    remainingToday: "今日剩余",
    newNote: "新建",
    aiFastPuskica: "AI快速笔记",
    uploadImageDescription: "上传图片并输入科目 - AI自动提取公式、定义、日期和关键人物！",
    subjectPlaceholder: "科目名称（例如：数学）",
    changeImage: "更换图片",
    addImage: "添加图片",
    extracting: "提取中...",
    create: "创建",
    historyBySubjects: "按科目历史",
    total: "总计",
    noPuskiceYet: "还没有笔记",
    uploadImageForExtraction: "上传图片并在上方输入科目进行快速AI提取！",
    puskica: "笔记",
    close: "关闭",
    pleaseEnterSubject: "请输入科目名称。",
    pleaseAddImage: "请添加图片进行提取。",
    mustBeLoggedIn: "您必须登录。",
    extractionFailed: "提取失败",
    success: "成功！✨",
    aiExtractedInfo: "AI已提取信息并创建笔记。",
    somethingWentWrong: "出了点问题。",
    cannotDeletePuskica: "无法删除笔记。",
    deleted: "已删除",
    puskicaDeleted: "笔记已删除。",
    other: "其他",
    puskiceCount: "笔记",
    // Direct Chat
    messages: "消息",
    newChat: "新聊天",
    enterUserEmail: "输入您想联系的用户邮箱：",
    userNotFound: "未找到用户",
    noUserWithEmail: "没有该邮箱的用户。",
    cannotMessageSelf: "您不能给自己发消息。",
    conversationCreated: "对话已创建",
    canNowChatWith: "您现在可以与",
    cannotCreateConversation: "无法创建对话。",
    messageNotSent: "消息未发送。",
    noMessages: "没有消息",
    startConversation: "与某人开始对话！",
    unknown: "未知",
    // Quick Actions
    explainSimply: "简单解释",
    createSummary: "创建摘要",
    makeQuiz: "制作测验",
    helpWithHomework: "作业帮助",
    examMode: "考试模式",
    explainPrompt: "请用最简单的方式逐步解释这个主题：",
    summaryPrompt: "请创建这个主题的清晰、有条理的摘要：",
    quizPrompt: "请创建一个包含5道选择题的简短测验，关于：",
    homeworkPrompt: "我需要作业帮助。请引导我解决这个问题：",
    examPrompt: "我正在准备考试。请给我直接、清晰的答案：",
    // Welcome Message
    heyThere: "你好！👋",
    personalTutor: "我是你的私人AI导师。我在这里帮助你学习，理解困难的主题，并在学业上取得成功。你今天想学什么？",
    tryTyping: "试着输入问题或使用下面的快捷按钮 ✨",
    homeworkHelp: "逐步作业帮助",
    understandTopics: "轻松理解困难主题",
    practiceQuizzes: "用测验练习",
    // Tabs
    aiChat: "AI聊天",
    puskiceTab: "笔记",
    messagesTab: "消息",
  },
  ja: {
    menu: "メニュー",
    lightMode: "ライトモード",
    darkMode: "ダークモード",
    editProfile: "プロフィール編集 / アバター",
    chatHistory: "チャット履歴",
    clearHistory: "履歴を削除",
    checkUpdates: "更新を確認",
    admin: "管理者",
    signOut: "ログアウト",
    upgradeToPro: "Proにアップグレード",
    languages: "言語",
    askAnything: "何でも聞いて...",
    takePhoto: "写真を撮る",
    chooseFromGallery: "ギャラリーから選択",
    sharePdf: "PDFを共有",
    voiceChat: "音声チャット",
    send: "送信",
    days: "日",
    lifetimePro: "ライフタイム Pro",
    cancel: "キャンセル",
    enter: "入る",
    password: "パスワード...",
    wrongPassword: "パスワードが間違っています",
    checkingUpdates: "更新を確認中…",
    pleaseWait: "お待ちください。",
    error: "エラー",
    cannotCheckUpdate: "更新を確認できません。",
    addMessage: "メッセージを追加...",
    askAboutImage: "この画像について質問...",
    speakNow: "今話してください",
    listening: "聞いています...",
    processing: "処理中...",
    tapToSpeak: "タップして話す",
    stopListening: "停止",
    // Puskice
    myPuskice: "マイノート",
    unlimited: "無制限",
    remainingToday: "今日の残り",
    newNote: "新規",
    aiFastPuskica: "AIクイックノート",
    uploadImageDescription: "画像をアップロードして科目を入力 - AIが自動的に公式、定義、日付、重要人物を抽出します！",
    subjectPlaceholder: "科目名（例：数学）",
    changeImage: "画像を変更",
    addImage: "画像を追加",
    extracting: "抽出中...",
    create: "作成",
    historyBySubjects: "科目別履歴",
    total: "合計",
    noPuskiceYet: "まだノートがありません",
    uploadImageForExtraction: "上で画像をアップロードして科目を入力し、AIで高速抽出！",
    puskica: "ノート",
    close: "閉じる",
    pleaseEnterSubject: "科目名を入力してください。",
    pleaseAddImage: "抽出用の画像を追加してください。",
    mustBeLoggedIn: "ログインが必要です。",
    extractionFailed: "抽出に失敗しました",
    success: "成功！✨",
    aiExtractedInfo: "AIが情報を抽出し、ノートを作成しました。",
    somethingWentWrong: "問題が発生しました。",
    cannotDeletePuskica: "ノートを削除できません。",
    deleted: "削除されました",
    puskicaDeleted: "ノートが削除されました。",
    other: "その他",
    puskiceCount: "ノート",
    // Direct Chat
    messages: "メッセージ",
    newChat: "新しいチャット",
    enterUserEmail: "メッセージを送りたいユーザーのメールを入力：",
    userNotFound: "ユーザーが見つかりません",
    noUserWithEmail: "そのメールアドレスのユーザーはいません。",
    cannotMessageSelf: "自分にメッセージを送ることはできません。",
    conversationCreated: "会話が作成されました",
    canNowChatWith: "チャットできるようになりました：",
    cannotCreateConversation: "会話を作成できません。",
    messageNotSent: "メッセージが送信されませんでした。",
    noMessages: "メッセージがありません",
    startConversation: "誰かと会話を始めましょう！",
    unknown: "不明",
    // Quick Actions
    explainSimply: "簡単に説明",
    createSummary: "要約を作成",
    makeQuiz: "クイズを作成",
    helpWithHomework: "宿題の助け",
    examMode: "試験モード",
    explainPrompt: "このトピックを最も簡単な方法でステップバイステップで説明してください：",
    summaryPrompt: "このトピックの明確で整理された要約を作成してください：",
    quizPrompt: "次についての5問の選択問題の短いクイズを作成してください：",
    homeworkPrompt: "宿題の助けが必要です。この問題を通して案内してください：",
    examPrompt: "試験の準備をしています。直接的で明確な答えをください：",
    // Welcome Message
    heyThere: "こんにちは！👋",
    personalTutor: "私はあなたの個人AIチューターです。学習を助け、難しいトピックを理解し、勉強で成功できるようサポートします。今日は何を学びたいですか？",
    tryTyping: "質問を入力するか、下のクイックアクションボタンを使ってください ✨",
    homeworkHelp: "ステップバイステップの宿題サポート",
    understandTopics: "難しいトピックを簡単に理解",
    practiceQuizzes: "クイズで練習",
    // Tabs
    aiChat: "AIチャット",
    puskiceTab: "ノート",
    messagesTab: "メッセージ",
  },
  ar: {
    menu: "القائمة",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    editProfile: "تعديل الملف / الصورة",
    chatHistory: "سجل المحادثات",
    clearHistory: "مسح السجل",
    checkUpdates: "التحقق من التحديثات",
    admin: "المسؤول",
    signOut: "تسجيل الخروج",
    upgradeToPro: "الترقية إلى Pro",
    languages: "اللغات",
    askAnything: "اسأل أي شيء...",
    takePhoto: "التقاط صورة",
    chooseFromGallery: "اختر من المعرض",
    sharePdf: "مشاركة PDF",
    voiceChat: "الدردشة الصوتية",
    send: "إرسال",
    days: "أيام",
    lifetimePro: "Pro مدى الحياة",
    cancel: "إلغاء",
    enter: "دخول",
    password: "كلمة المرور...",
    wrongPassword: "كلمة مرور خاطئة",
    checkingUpdates: "جاري التحقق من التحديثات…",
    pleaseWait: "يرجى الانتظار.",
    error: "خطأ",
    cannotCheckUpdate: "لا يمكن التحقق من التحديثات.",
    addMessage: "أضف رسالة...",
    askAboutImage: "اسأل عن هذه الصورة...",
    speakNow: "تحدث الآن",
    listening: "أستمع...",
    processing: "جاري المعالجة...",
    tapToSpeak: "انقر للتحدث",
    stopListening: "توقف",
    // Puskice
    myPuskice: "ملاحظاتي",
    unlimited: "غير محدود",
    remainingToday: "المتبقي اليوم",
    newNote: "جديد",
    aiFastPuskica: "ملاحظة سريعة بالذكاء الاصطناعي",
    uploadImageDescription: "ارفع صورة وأدخل المادة - الذكاء الاصطناعي يستخرج تلقائياً الصيغ والتعريفات والتواريخ والشخصيات الرئيسية!",
    subjectPlaceholder: "اسم المادة (مثل: الرياضيات)",
    changeImage: "تغيير الصورة",
    addImage: "إضافة صورة",
    extracting: "جاري الاستخراج...",
    create: "إنشاء",
    historyBySubjects: "السجل حسب المواد",
    total: "المجموع",
    noPuskiceYet: "لا توجد ملاحظات بعد",
    uploadImageForExtraction: "ارفع صورة وأدخل المادة أعلاه للاستخراج السريع بالذكاء الاصطناعي!",
    puskica: "ملاحظة",
    close: "إغلاق",
    pleaseEnterSubject: "الرجاء إدخال اسم المادة.",
    pleaseAddImage: "الرجاء إضافة صورة للاستخراج.",
    mustBeLoggedIn: "يجب تسجيل الدخول.",
    extractionFailed: "فشل الاستخراج",
    success: "نجاح! ✨",
    aiExtractedInfo: "استخرج الذكاء الاصطناعي المعلومات وأنشأ ملاحظة.",
    somethingWentWrong: "حدث خطأ ما.",
    cannotDeletePuskica: "لا يمكن حذف الملاحظة.",
    deleted: "تم الحذف",
    puskicaDeleted: "تم حذف الملاحظة.",
    other: "أخرى",
    puskiceCount: "ملاحظات",
    // Direct Chat
    messages: "الرسائل",
    newChat: "محادثة جديدة",
    enterUserEmail: "أدخل بريد المستخدم الذي تريد مراسلته:",
    userNotFound: "المستخدم غير موجود",
    noUserWithEmail: "لا يوجد مستخدم بهذا البريد.",
    cannotMessageSelf: "لا يمكنك مراسلة نفسك.",
    conversationCreated: "تم إنشاء المحادثة",
    canNowChatWith: "يمكنك الآن الدردشة مع",
    cannotCreateConversation: "لا يمكن إنشاء محادثة.",
    messageNotSent: "لم يتم إرسال الرسالة.",
    noMessages: "لا توجد رسائل",
    startConversation: "ابدأ محادثة مع شخص ما!",
    unknown: "غير معروف",
    // Quick Actions
    explainSimply: "اشرح ببساطة",
    createSummary: "أنشئ ملخصاً",
    makeQuiz: "أنشئ اختباراً",
    helpWithHomework: "مساعدة في الواجب",
    examMode: "وضع الامتحان",
    explainPrompt: "من فضلك اشرح هذا الموضوع بأبسط طريقة ممكنة، خطوة بخطوة:",
    summaryPrompt: "من فضلك أنشئ ملخصاً واضحاً ومنظماً لهذا الموضوع:",
    quizPrompt: "من فضلك أنشئ اختباراً قصيراً من 5 أسئلة اختيار من متعدد حول:",
    homeworkPrompt: "أحتاج مساعدة في واجبي. من فضلك أرشدني خلال هذه المسألة:",
    examPrompt: "أستعد للامتحان. من فضلك أعطني إجابات مباشرة وواضحة:",
    // Welcome Message
    heyThere: "مرحباً! 👋",
    personalTutor: "أنا معلمك الشخصي بالذكاء الاصطناعي. أنا هنا لمساعدتك على التعلم، وفهم المواضيع الصعبة، والتفوق في دراستك. ماذا تريد أن تتعلم اليوم؟",
    tryTyping: "جرب كتابة سؤال أو استخدم أزرار الإجراء السريع أدناه ✨",
    homeworkHelp: "مساعدة في الواجب خطوة بخطوة",
    understandTopics: "افهم المواضيع الصعبة بسهولة",
    practiceQuizzes: "تدرب مع الاختبارات",
    // Tabs
    aiChat: "دردشة الذكاء الاصطناعي",
    puskiceTab: "ملاحظات",
    messagesTab: "رسائل",
  },
};

export const languageNames: Record<Language, string> = {
  sr: "Srpski",
  en: "English",
  de: "Deutsch",
  fr: "Français",
  es: "Español",
  it: "Italiano",
  ru: "Русский",
  zh: "中文",
  ja: "日本語",
  ar: "العربية",
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "sr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
